apiVersion: v1
kind: Service
metadata:
  name: zadig-server
  namespace: test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: zadig-nginx
  sessionAffinity: None
  type: ClusterIP

